# Generated by Django 3.2.3 on 2021-07-04 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('iproveedor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de proveedor')),
                ('fotoproveedor', models.ImageField(null=True, upload_to='Proveedores')),
                ('nombreproveedor', models.CharField(max_length=16, verbose_name='Nombre de proveedor')),
                ('Telefonoproveedor', models.CharField(max_length=12, verbose_name='telefono de proveedor')),
                ('direccionproveedor', models.CharField(max_length=100, verbose_name='telefono de proveedor')),
                ('emailproveedor', models.CharField(max_length=100, verbose_name='telefono de proveedor')),
                ('contrasenaproveedor', models.CharField(max_length=4, verbose_name='contraseña')),
                ('monedapago', models.CharField(max_length=7, verbose_name='tipo de moneda de pago')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('monproducto', models.CharField(max_length=100, verbose_name='Nombre de producto')),
                ('valorproducto', models.CharField(max_length=100, verbose_name='valor producto')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ground_Zero.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de pais')),
                ('nombrepais', models.CharField(max_length=50, verbose_name='Nombre del país')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ground_Zero.proveedor')),
            ],
        ),
    ]
