# Generated by Django 3.2.3 on 2021-07-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ground_Zero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='Proveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ground_Zero.pais'),
            preserve_default=False,
        ),
    ]
